trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:

- script: dotnet test ./TableTopInc.API/TableTopInc.API.Test/TableTopInc.API.Test.csproj --configuration $(buildConfiguration) --logger trx
  displayName: dotnet test
  
- script: dotnet publish ./TableTopInc.API/TableTopInc.API.Public/TableTopInc.API.Public.csproj --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY
  displayName: dotnet publish

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1
  