trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:

- script: |
    dotnet test dotnetcore-tests --configuration $(buildConfiguration) --logger trx ./TableTopInc.API/TableTopInc.API.Test/TableTopInc.API.Test.csproj

- script: |
    dotnet publish --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY ./TableTopInc.API/TableTopInc.API.Public/TableTopInc.API.Public.csproj

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- task: PublishBuildArtifacts@1